version: '3.9'

services:
  dev_db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    ports:
      - '5432:5432'
    networks:
      - myNetwork
networks:
  myNetwork:
